language: java
jdk: openjdk7
env:
  global:
    secure: HfaLTavTuyClB2pOaglUTxSJHek9GLfxNTdrXQEXxJhSrlYBKLXzuhn9H0kYl0I1km0jYp5g61/h2GtjRKfs1M7L5HUJsf2T/Iqc5RZvrVO7utDavMx1KqrzaMOY6VILyftuK1fcaYYOIBiAMPm+iw4irEL/QZjCaXm8Vn5ihbs=
deploy:
  provider: heroku
  api_key:
    secure: AmLVQZEk3ZG688EPrZAbFztvun8qHVkTMrIxqw5TN+hCJg2GQBWMzo+OFT1BDP6WvwtWQ/f07ik2SHlgRMtAQ3SCRy8T8PjU351zFyh2Yok7Z0zBUnnrQ2FlQ1IFLqCn9iFVK7cFoS3uZCsQt9f2swJlE7odHHzAZGPoVrkux+M=
  app: geitamamma-production
  on:
    repo: geitamamma/TicTacToe
before_install:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- git remote add heroku git@heroku.com:geitamamma-staging.git
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- y | heroku keys:add
- git push heroku master
script:
- sh bin/compile
- sh bin/package
- export STAGING_SERVER=http://geitamamma-staging.herokuapp.com/
- sh bin/selenium_test_xvfb
