language: java
jdk: openjdk7
deploy:
  provider: heroku
  api_key:
    secure: Q29M6Nu3fNquN9VCq14YNIvkLu9X+ViwGEt2Tm5W+NQbaGCqOu7GZLwP6eRIwFmNFa68xWVh1h9NpYyDBuzEHJZqk2BG51dMlonNjxAvS6u89R5Qid4VDD9FbobBBI+l/0J8odSJuO5ZK9uPvpeoAyH9Ld8Yl0doZtrITDADtWo=
  app: geitamamma-staging
  on:
    repo: geitamamma/TicTacToe
before_install:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - git remote add heroku git@heroku.com:geitamamma-staging.git
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - heroku keys:add
  - git push heroku master
script:
  - sh bin/compile
  - sh bin/package
